# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_auto_20160719_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='age',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
