# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_auto_20160722_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='recorded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='recorded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='recorded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='recorded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
